---
abstract: 'Set and detect project environment via .environment file.'
author:
  - 'Roman F. <romanf@cpan.org>'
build_requires:
  Test::Most: 0
  lib::abs: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Project-Environment
requires:
  Carp: 0
  Class::Inspector: 0
  File::Spec: 0
  Module::Path: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Role::Flyweight: 0
  MooseX::Types::Path::Tiny: 0
  Path::FindDev: 0
  Path::Tiny: 0
  overload: 0
  version: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Project-Environment
  repository: git://github.com/moltar/Project-Environment.git
version: v1.2.0
